[build]
  command = "hugo --gc --minify"
  publish = "public"
  
[context.production.environment]
  HUGO_VERSION = "0.126.3"  # GitHub'da mevcut SON STABIL EXTENDED SÜRÜM
  HUGO_EXTENDED = "true"    # Extended özelliği aktif